### ISSUE TITLE
Question about future work (tag sub-entity of the same class)

### ISSUE THREAD

**Issue by poteminr** [SinaLab/ArabicNER#4]
Thank you for your article. 
I am solving a nested ner task for clinical notes and using similar architecture with some additions like contrastive learning etc.
 So I have the same problem with nested entities of the same type. What’s your idea for a solution? 

Any suggestions would be helpful for me.

**Comment by mohammedkhalilia** [comment]
There are few approaches to nested NER listed below. I hope you will find them helpful. I believe some of them handle nested entities of same type.

* <div class="csl-entry">Shibuya, T., &#38; Hovy, E. (2020). Nested Named Entity Recognition via Second-best Sequence Learning and Decoding. <i>Transactions of the Association for Computational Linguistics</i>, <i>8</i>, 605–620. https://doi.org/10.1162/TACL_A_00334</div>

* <div class="csl-entry">Katiyar, A., &#38; Cardie, C. (2018). Nested named entity recognition revisited. <i>Proceedings of the NAACL HLT 2018</i>, <i>1</i>, 861--871. https://doi.org/10.18653/v1/n18-1079</div>

* <div class="csl-entry">WANG, J., Shou, L., Chen, K., &#38; Chen, G. (2020). Pyramid: A Layered Model for Nested Named Entity Recognition. <i>Proceedings of the ACL 2020</i>, 5918--5928. https://doi.org/10.18653/v1/2020.acl-main.525</div>

* <div class="csl-entry">Sohrab, M. G., &#38; Miwa, M. (2020). Deep exhaustive model for nested named entity recognition. <i>Proceedings of the 2018 Conference on Empirical Methods in Natural Language Processing, EMNLP 2018</i>. https://doi.org/10.18653/v1/d18-1309</div>

* <div class="csl-entry">Ju, M., Miwa, M., &#38; Ananiadou, S. (2018). A Neural Layered Model for Nested Named Entity Recognition. <i>NAACL HLT 2018 - 2018 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies - Proceedings of the Conference</i>, <i>1</i>, 1446–1459. https://doi.org/10.18653/V1/N18-1131</div>

**Comment by poteminr** [comment]
So approaches from this articles handle nested entities of the same type, but main question is “Can we handle entities of the same type using architecture from your article with some additions (and what additions)?” without changing architecture to a pyramid network or span-based network.

**Comment by mohammedkhalilia** [comment]
We have shared task for Wojood NER and the results will be published in ArabicNLP/EMNLP 2023. In the shared task I believe some participants handled nested entity mentions with same type.
